/*
 * This source file was generated by the Gradle 'init' task
 */
package com.codewithjas;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        FilterDemo classUnderTest = new FilterDemo();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
